### PR TITLE
integrated the new type DepthMap into the velodyne LaserScanner task

### PR DESCRIPTION
**Pull request by hemker**
i integrated the new DepthMap type into the LaserScanner task and removed the deprecated type MultiLevelLaserScan

### CODE REVIEW

**Comment by saarnold** [comment]
Ok thanks!
From my point of view this can be merged.

**Comment by goldhoorn** [comment]
@saarnold: you have now merge permissions

**Comment by goldhoorn** [comment]
@hemker: please rebase to master so that this patch can be applied

**Comment by saarnold** [comment]
@hemker you have to do a rebase with the head of the new_depth_map branch, otherwise I can not apply your patch.

**Comment by hemker** [comment]
@saarnold done. thanks for the reminder.

**Pull request merged**
